[package]
name = "vkot"
version = "0.1.0"
authors = ["asrcpq <asrcpq@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.27"
anyhow = "1"

triangles = {path = "../triangles"}
vkot_client = {path = "../vkot_client"}
skey = {path = "../skey", features = ["winit_key"]}
